# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 18:29
from __future__ import unicode_literals

from django.db import migrations
from polls.utils import yaml_loader

# filepath_companies = "polls/static/polls/companiesList.yaml"
# companiesList = yaml_loader(filepath_companies).get("companies")


def add_companies(apps, schema_editor):
	companiesList = yaml_loader("polls/static/polls/companiesList.yaml").get("companies")
	Company = apps.get_model('polls', 'Company')
	for company in companiesList:
		Company.objects.create(name=company)


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [migrations.RunPython(add_companies)
    ]
